name: Pull-Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run gradle build
        run: ./gradlew build

      - name: homebrew & ganache
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" && brew update && brew install --cask ganache

      - name: Run Tests
        run: ./gradlew jsTest
